# Generated by Django 3.2.15 on 2022-09-25 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 25, 17, 46, 8, 407770)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 17, 46, 8, 407770)),
        ),
    ]
