# Generated by Django 3.2.15 on 2022-10-05 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20220925_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 10, 6, 15, 406090)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 10, 6, 15, 406090)),
        ),
    ]
