# Generated by Django 3.2.15 on 2022-10-12 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20221012_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkin_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 13, 7, 10, 72515)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkout_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 13, 7, 10, 72515)),
        ),
    ]
